name:                pqr
version:             0.1.0.0
github:              "andcol/proto-quipper-r"
license:             MIT
author:              "Andrea Colledan"
maintainer:          "andrea.colledan@unibo.it"
copyright:           "2024 Andrea Colledan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pqr#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- extra
- hspec
- process
- filepath
- parsec
- argparser
- timeit

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-top-binds
- -Wincomplete-patterns
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  pqr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pqr

tests:
  pqr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pqr
