site_name: QuRA
site_url: !ENV READTHEDOCS_CANONICAL_URL
theme:
  name: readthedocs
extra_javascript:
    - javascript/readthedocs.js
markdown_extensions:
  - pymdownx.snippets

nav:
  - The Tool:
    - Installation: tool/installation.md
    - Getting started: tool/getting-started.md
    - Extending QuRA : tool/extensions.md
  - The PQ Language:
    - Overview : language/overview.md
    - The fold primitive : language/fold.md
    - Prelude : language/prelude.md